-- quiz_categories table seeds here
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Onboarding', 'This welcome quiz will teach how to use this app!', 'https://web.compass.lighthouselabs.ca/quizzes/34/quiz_submissions/new?activity_id=316', 123456, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'CSS', 'How do we style HTML and make it look nice?', 'https://web.compass.lighthouselabs.ca/quizzes/34/quiz_submissions/new?activity_id=316', 123456, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Web Forms', 'How do users enter and provide data ?', 'https://web.compass.lighthouselabs.ca/quizzes/35/quiz_submissions/new?activity_id=317', 234567, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'DOM Events', 'How do we get around webpage elements?', 'https://web.compass.lighthouselabs.ca/quizzes/36/quiz_submissions/new?activity_id=320', 345678, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'What is AJAX?', 'How do we do cool stuff and not reload the page?', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 345679, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'jQuery', 'How can I do javascript even lazier?', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, true, 600, 47, true);


--For my purposes only do not merge into master
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'What is love', 'This welcome quiz will teach how to use this app!', 'https://web.compass.lighthouselabs.ca/quizzes/34/quiz_submissions/new?activity_id=316', 123456, false, 600, 101, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Baby Dont Hurt Me', 'Baby Dont Hurt Me', 'https://web.compass.lighthouselabs.ca/quizzes/34/quiz_submissions/new?activity_id=316', 123456, false, 600, 101, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Dont Hurt Me', 'Dont Hurt Me', 'https://web.compass.lighthouselabs.ca/quizzes/35/quiz_submissions/new?activity_id=317', 234567, false, 600, 101, false);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'No More', 'No More', 'https://web.compass.lighthouselabs.ca/quizzes/36/quiz_submissions/new?activity_id=320', 345678, false, 600, 101, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Vogue', 'Im blue', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 345679, false, 600, 101, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Burger King Trivia', 'Burger King Trivia', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, true, 600, 101, true);

