-- quiz_categories table seeds
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Onboarding', 'This welcome quiz will teach how to use this app!', 'https://web.compass.lighthouselabs.ca/quizzes/34/quiz_submissions/new?activity_id=316', 123456, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'CSS', 'How do we style HTML and make it look nice?', 'https://web.compass.lighthouselabs.ca/quizzes/34/quiz_submissions/new?activity_id=316', 123456, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Web Forms', 'How do users enter and provide data ?', 'https://web.compass.lighthouselabs.ca/quizzes/35/quiz_submissions/new?activity_id=317', 234567, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'DOM Events', 'How do we get around webpage elements?', 'https://web.compass.lighthouselabs.ca/quizzes/36/quiz_submissions/new?activity_id=320', 345678, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'What is AJAX?', 'How do we do cool stuff and not reload the page?', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 345679, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'jQuery', 'How can I do javascript even lazier?', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Private Active Quiz', 'How do we get publish a private quiz?', 'https://web.compass.lighthouselabs.ca/quizzes/36/quiz_submissions/new?activity_id=320', 345679, false, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Public Inactive Quiz', 'How do we make our quiz inactive?', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 345679, true, 600, 47, false);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Private Inactive Quiz', 'How can we make our private quiz inactive?', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, false, 600, 47, false);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (1, 'Private Inactive Quiz', 'How can we make our private quiz inactive?', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, false, 600, 47, false);

-- for design testing
<<<<<<< HEAD
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (5, 'Star Wars Trivia', 'From Courasant to the Outer Rimm, test your fandom level!', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (5, 'Game of Thrones Trivia', 'From Kings Landing to Winterfell, winter is coming!', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, true, 600, 47, true);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (5, 'Superheroes', 'From the MCU to DCU and beyond!', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, true, 600, 47, true);
=======
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (5, 'Star Wars Trivia', 'From Courasant to the Outer Rimm, test your fandom level!', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, false, 600, 47, false);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (5, 'Game of Thrones Trivia', 'From Kings Landing to Winterfell, winter is coming!', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, false, 600, 47, false);
INSERT INTO quizzes (quiz_category_id, name, description, url_link, pin, public, time_limit , user_id, active) VALUES (5, 'Superheroes', 'From the MCU to DCU and beyond!', 'https://web.compass.lighthouselabs.ca/quizzes/14/quiz_submissions/new?activity_id=63', 456789, false, 600, 47, false);
>>>>>>> master
