INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (2, null, 'Which would take priority, an id (#my-id) in a CSS file or inline styling (style="...")?', 'Inside scoop...', 1, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (2, null, 'What colour would render given the hex code #FF0000', 'Nothing is stopping you...', 2, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (2, null, 'Which of the following CSS selector has the highest specificity?', 'Check your wallet...' , 3, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (2, null, 'Explain what CSS !important means, and when would you use it?', 'Bad doggie...' , 4, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (2, null, 'In what order do the following surround an html element according to the Box Model?', 'Peanut Butter Margarine...', 5, null, null, null, 47, true);

INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (3, null, 'Would a search form submission typically use GET or POST requests? (ex. Google)', 'You can get it...', 2, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (3, null, 'A site shows a form to edit your contact info, and shows a Save button (to submit the changes) and Cancel button (to go back to the main page). How should the Cancel button be implemented?', 'Take off, eh...', 3, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (3, null, 'Explain what CSS !important means, and when would you use it?', 'All is well that...', 4, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (3, null, 'In what order do the following surround an html element according to the Box Model?', 'Mailing a letter...', 5, null, null, null, 47, true);

-- questions for design test data
-- star wars
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (11, null, 'Who is the father of Darth Vader?', 'Immaculate...', 1, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (11, null, 'How old is Yoda?', 'Yoda as a millenium...', 2, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (11, null, 'Who is the last Jedi?', 'Ray of sunshine...', 3, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (11, null, 'What does not destroy planets?', 'Yess-ah...', 4, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (11, null, 'What planet do Ewoks live on?', 'You yaven a good time...', 5, null, null, null, 47, true);
-- game of thrones
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (12, null, 'How did Ned Stark die?', 'Watch your head...', 1, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (12, null, 'How did Joffrey Baratheon die?', 'Watch your head...', 2, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (12, null, 'How did Tywin Lannister die?', 'Cross that bridge...', 3, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (12, null, 'How did Ramsay Bolton die?', 'Best friend of man...', 4, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (12, null, 'How did Littlefinger die?', 'Small and pointy...', 5, null, null, null, 47, true);
-- game of thrones
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (13, null, 'How did Iron Man die?', 'Watch your head...', 1, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (13, null, 'How did Black Widow die?', 'Watch your head...', 2, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (13, null, 'How did Spiderman get his powers', 'Itsy bitsy biter...', 3, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (13, null, 'Where does Wonder Woman hail from?', 'Thirsty...', 4, null, null, null, 47, true);
INSERT INTO questions (quiz_id, question_category_id, question, hint, sort_order, time_limit, bg_image_url, color, user_id, active) VALUES (13, null, 'What will Nick Fury not eat?', 'Careful with knives...', 5, null, null, null, 47, true);
